#!/bin/sh
# Build libtar.a from bundled source without requiring the full autotools setup.
# Usage: sh build_libtar.sh [install-prefix]
#   Default prefix: ./build
set -e

PREFIX="${1:-$(dirname "$0")/build}"
SRCDIR="$(dirname "$0")"
PREFIX="$(cd "$SRCDIR" && mkdir -p build && cd build && pwd)"

LISTHASH_PREFIX="libtar"
LISTHASH_DIR="$SRCDIR/listhash"
LIB_DIR="$SRCDIR/lib"
BUILD_TMP="$SRCDIR/build_tmp"

mkdir -p "$BUILD_TMP" "$PREFIX/include" "$PREFIX/lib"

echo "=== Generating listhash headers and sources ==="
# Substitute @LISTHASH_PREFIX@ in the .in templates
for tmpl in "$LISTHASH_DIR"/*.h.in "$LISTHASH_DIR"/*.c.in; do
    [ -f "$tmpl" ] || continue
    out="$BUILD_TMP/$(basename "$tmpl" .in | sed "s/listhash/${LISTHASH_PREFIX}_listhash/g; s/list$/${LISTHASH_PREFIX}_list/g; s/hash$/${LISTHASH_PREFIX}_hash/g")"
    sed "s|@LISTHASH_PREFIX@|${LISTHASH_PREFIX}|g; s|@configure_input@|Generated by build_libtar.sh|g" "$tmpl" > "$out"
    echo "  Generated: $out"
done

echo "=== Compiling libtar ==="
CFLAGS="-I$LIB_DIR -I$BUILD_TMP -g -O2"

OBJS=""
for src in "$LIB_DIR"/*.c "$BUILD_TMP"/*.c; do
    [ -f "$src" ] || continue
    obj="$BUILD_TMP/$(basename "$src" .c).o"
    echo "  CC $src"
    gcc $CFLAGS -c -o "$obj" "$src"
    OBJS="$OBJS $obj"
done

echo "=== Creating libtar.a ==="
ar cru "$PREFIX/lib/libtar.a" $OBJS
ranlib "$PREFIX/lib/libtar.a"

echo "=== Installing headers ==="
cp "$LIB_DIR/libtar.h" "$PREFIX/include/"
# Make listhash header available as libtar_listhash.h
cp "$BUILD_TMP/libtar_listhash.h" "$PREFIX/include/" 2>/dev/null || true

echo "=== Done ==="
echo "  libtar.a : $PREFIX/lib/libtar.a"
echo "  libtar.h : $PREFIX/include/libtar.h"
