#!/bin/bash

set -e

if [ "$1" = "configure" ]; then

    if [ -f /etc/jobarranger/web/jam.config.php.debconf ] && [ ! -f /etc/jobarranger/web/jam.config.php ]; then
    	echo "Removing the backup file jam.config.php.debconf since the old jam.config.php remains."
    	mv /etc/jobarranger/web/jam.config.php.debconf /etc/jobarranger/web/jam.config.php
        cp /usr/share/jobarranger/api/app/config/jam.config.php /etc/jobarranger/web/jam.config.php.new
    fi

    # enable Apache configuration
    #a2enconf jobarranger-ui jobarranger-api

    # Enable the Apache2 rewrite and header module
    a2enmod rewrite
    a2enmod headers

    # restart services
    chown -R www-data.www-data /etc/jobarranger/web
    chown -R www-data.www-data /usr/share/jobarranger
    systemctl daemon-reload
    systemctl restart apache2
    systemctl enable jam-cleanup.service

    echo "JobArranger has been installed successfully"
fi
