## Process this file with automake to produce Makefile.in

SUBDIRS = \
    zbxalgo \
    zbxcommon \
    zbxcomms \
    zbxcommshigh \
    zbxconf \
    zbxcrypto \
    zbxdb \
    zbxdbcache \
    zbxdbhigh \
    zbxexec \
    zbxicmpping \
    zbxjson \
    zbxlog \
    zbxmedia \
    zbxmemory \
    zbxnix \
    zbxself \
    zbxserver \
    zbxsys \
    zbxsysinfo

DIST_SUBDIRS = $(SUBDIRS)
