#!/bin/bash

# Add Job Arranger user
/usr/sbin/useradd -c "Job Arranger user" \
        -s /sbin/nologin -r -d /etc/zabbix zabbix 2> /dev/null || :

if [ -f /etc/jobarranger/jobarg_server.conf ]; then
    cp /etc/jobarranger/jobarg_server.conf /etc/jobarranger/jobarg_server.conf.new
fi
if [ -f /etc/jobarranger/jobarg_monitor.conf ]; then
    cp /etc/jobarranger/jobarg_monitor.conf /etc/jobarranger/jobarg_monitor.conf.new
fi


exit 0
