#!/bin/bash

# Add Job Arranger user
/usr/sbin/useradd -c "Job Arranger user" \
        -s /sbin/nologin -r -d /etc/zabbix zabbix 2> /dev/null || :

if [ -f /etc/jobarranger/jobarg_server.conf ]; then
    mv /etc/jobarranger/jobarg_server.conf /etc/jobarranger/jobarg_server.conf.debconf
fi
if [ -f /etc/jobarranger/jobarg_monitor.conf ]; then
    mv /etc/jobarranger/jobarg_monitor.conf /etc/jobarranger/jobarg_monitor.conf.debconf

fi

exit 0
